In [2]:
import numpy as np
arr = np.array([10,20,1.2,1.5])
print(arr)

[10.  20.   1.2  1.5]


In [3]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [4]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Floor Division: [5 5 6]
Modulus: [0 0 0]
Power: [100 400 900]


In [5]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
# Square Root
print("\nSquare Root:", np.sqrt(arr))
# Square
print("Square:", np.square(arr))
# Cube (Power 3)
print("Cube:", np.power(arr, 3))
# Absolute Value
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
# Exponential (e^x)
print("\nExponential:", np.exp(arr))
# Natural Logarithm
print("\nNatural Log:", np.log(arr))
# Base-10 Logarithm
print("Log Base 10:", np.log10(arr))
# Sine
print("\nSine:", np.sin(arr))
# Cosine
print("Cosine:", np.cos(arr))
# Tangent
print("Tangent:", np.tan(arr))
# Round Values
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
# Ceiling
print("Ceiling:", np.ceil(decimal))
# Floor
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [6]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[20 30]
 [50 60]]
[40 50 60]
[30 60 90]


In [7]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [8]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[10 40]
 [20 50]
 [30 60]]


In [9]:
arr = np.full((3, 4), 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [10]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27


In [12]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1, 11, 5))
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))
print(np.random.normal(50, 10, 5))
print(np.random.uniform(10, 20, 5))
print(np.random.binomial(1, 0.5))
print(np.random.binomial(10, 0.7))
print(np.random.poisson(4, 5))

print(np.random.exponential(2, 5))

0.3590900825490244
[0.55601045 0.65114293 0.92009081 0.84256015 0.44109408]
[10  7  4  7  4]
DBMS
[53.06635111 44.44536715 31.1612574  51.20278389 41.74712915]
[17.64023646 11.1583899  13.08273746 13.46152138 13.17477584]
0
7
[3 6 6 5 3]
[0.80193788 0.83555053 2.62158181 0.1610181  0.83569184]


In [13]:
scalar = np.array(5)
vector = np.array([2, 5, 1])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.ones((3, 2, 2))
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(3, 2, 2)


In [14]:
A = np.arange(6).reshape(2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]]
A + B (element-wise add):
 [[1 2 3]
 [4 5 6]]
A.T  (transpose -> shape (3, 2) ):
 [[0 3]
 [1 4]
 [2 5]]
A.reshape(3, 2):
 [[0 1]
 [2 3]
 [4 5]]
A.flatten(): [0 1 2 3 4 5]


In [18]:

a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('a . b  (dot)   :', np.dot(a, b))
print('a x b  (cross) :', np.cross(a, b))

a . b  (dot)   : 7
a x b  (cross) : [ 2 11 -8]


In [21]:
import numpy as np
import numpy.linalg as la
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('L2 norm  ||a||_2 :', la.norm(a))         # sqrt(sum of squares)
print('L1 norm  ||a||_1 :', la.norm(a, 1))      # sum of absolute values
print('Linf norm        :', la.norm(a, np.inf)) # max absolute value

def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))

L2 norm  ||a||_2 : 3.7416573867739413
L1 norm  ||a||_1 : 6.0
Linf norm        : 3.0
cosine(a, b)     : 0.454


In [26]:
pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),
    (np.array([1, 2, 3]), np.array([3, 2, 1])),
    (np.array([2, 0, 0]), np.array([0, 5, 0])),
]

for i, (u, v) in enumerate(pairs, start=1):

  pass

In [27]:
A = np.array([[2., 1.],
              [1., 3.]])
B = np.array([[1., 0.],
              [4., 2.]])

print('A @ B (matrix multiply):\n', A @ B)
print('A.T   (transpose):\n', A.T)
print('inverse(A):\n', la.inv(A))
print('trace(A) = sum of diagonal:', np.trace(A))

A @ B (matrix multiply):
 [[ 6.  2.]
 [13.  6.]]
A.T   (transpose):
 [[2. 1.]
 [1. 3.]]
inverse(A):
 [[ 0.6 -0.2]
 [-0.2  0.4]]
trace(A) = sum of diagonal: 5.0


In [28]:
I = np.eye(2)                       # identity: 1s on the diagonal
print('Identity I:\n', I)
print('A @ inv(A) == I ?', np.allclose(A @ la.inv(A), I))
print('A symmetric?', np.allclose(A, A.T))
theta = np.radians(30)
Q = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print('Q orthogonal?', np.allclose(Q.T @ Q, I))


Identity I:
 [[1. 0.]
 [0. 1.]]
A @ inv(A) == I ? True
A symmetric? True
Q orthogonal? True


In [ ]:
M = np.array([[4., 2.],
              [2., 3.]])
P = np.array([[0., -1.],
              [1.,  0.]])

In [29]:
square = np.array([[0, 1, 1, 0],
                   [0, 0, 1, 1]], dtype=float)
S = np.array([[1.5, 0.0],
              [0.0, 0.5]])
t = np.radians(30)
R = np.array([[np.cos(t), -np.sin(t)],
              [np.sin(t),  np.cos(t)]])

scaled  = S @ square      # apply scaling
rotated = R @ square      # apply rotation
print('Rotated corners:\n', rotated)

Rotated corners:
 [[ 0.         0.8660254  0.3660254 -0.5      ]
 [ 0.         0.5        1.3660254  0.8660254]]


In [30]:
def close_loop(pts):
    # repeat the first point at the end so the polygon closes
    return np.hstack([pts, pts[:, :1]])

fig, ax = plt.subplots(figsize=(5, 5))
ax.plot(*close_loop(square),  marker='o', label='original')
ax.plot(*close_loop(scaled),  marker='o', label='scaled')
ax.plot(*close_loop(rotated), marker='o', label='rotated 30 deg')
ax.axhline(0, color='gray', lw=0.5); ax.axvline(0, color='gray', lw=0.5)
ax.set_aspect('equal'); ax.legend(); ax.set_title('Linear transformations')
plt.show()

NameError: name 'plt' is not defined